version: '3'
services:
  shop_api:
    build:
      context: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - shop_db
      - shop_redis
    env_file:
      - .env
    volumes:
      - .:/app

  shop_db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  shop_redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
