# Generated by Django 6.0.2 on 2026-03-03 14:55

from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                help_text="Rating from 1 to 5",
            ),
        ),
    ]